version: 2.1
executors:
  dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      NUGET_XMLDOC_MODE: skip
jobs:
  build-test:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet build -c Debug
      - run: dotnet test -c Debug --no-build
  build-push:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet build -c Release -p:Version=${CIRCLE_TAG}
      - run: dotnet test -c Release --no-build
      - run: dotnet pack ./src/Ulid/Ulid.csproj -c Release --no-build -p:Version=${CIRCLE_TAG}
      - run: dotnet pack ./src/Ulid.Cli/Ulid.Cli.csproj -c Release --no-build -p:Version=${CIRCLE_TAG}
      - store_artifacts:
          path: ./src/Ulid/bin/Release
          destination: ./.Ulid/
      - run: dotnet nuget push ./src/Ulid/bin/Release/Ulid.${CIRCLE_TAG}.nupkg -s https://www.nuget.org/api/v2/package -k ${NUGET_KEY}
      - store_artifacts:
          path: ./src/Ulid.Cli/bin/Release
          destination: ./.Ulid/
      - run: dotnet nuget push ./src/Ulid.Cli/bin/Release/Ulid.Cli.${CIRCLE_TAG}.nupkg -s https://www.nuget.org/api/v2/package -k ${NUGET_KEY}
workflows:
  version: 2
  build-and-push:
    jobs:
      - build-test:
          filters:
            tags:
              only: /.*/
      - build-push:
          filters:
            tags:
              only: /^\d\.\d\.\d.*/
            branches:
              ignore: /.*/
